# -*- coding: utf-8 -*-
"""requirements.txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hfWAE2dejo1DDdPfxMplD1w_9EnjERHL
"""

# Commented out IPython magic to ensure Python compatibility.
# # Criação do arquivo requirements.txt no Google Colab
# %%writefile requirements.txt
# streamlit
# scikit-learn
# numpy
# pandas
#